INSERT INTO tb_user (username, password, created_at) VALUES ('Maria Brown', '12340987', '2025-06-15');
INSERT INTO tb_user (username, password, created_at) VALUES ('John Smith', 'senha4321', '2025-07-22');
INSERT INTO tb_user (username, password, created_at) VALUES ('Ana Souza', 'aB@123c', '2025-08-01');
INSERT INTO tb_user (username, password, created_at) VALUES ('Carlos Oliveira', '98765pass', '2025-09-10');
INSERT INTO tb_user (username, password, created_at) VALUES ('Jessica Lima', 'lima10jess', '2025-10-05');
INSERT INTO tb_user (username, password, created_at) VALUES ('Rafael Santos', 'rs@tech2025', '2025-11-28');
INSERT INTO tb_user (username, password, created_at) VALUES ('Fernanda Costa', 'Fc_2024!', '2023-01-18');
INSERT INTO tb_user (username, password, created_at) VALUES ('Pedro Almeida', 'pa12345678', '2021-02-09');
INSERT INTO tb_user (username, password, created_at) VALUES ('Julia Martins', 'Jm_password', '2021-03-25');
INSERT INTO tb_user (username, password, created_at) VALUES ('Lucas Pereira', 'Lp@dev#', '2022-04-12');
INSERT INTO tb_user (username, password, created_at) VALUES ('Beatriz Gomes', 'Bgomes55', '2023-05-30');
INSERT INTO tb_user (username, password, created_at) VALUES ('Alex Silva', 'passA123', '2024-03-10');
INSERT INTO tb_user (username, password, created_at) VALUES ('Brenda Rocha', 'Br_54321', '2024-05-25');
INSERT INTO tb_user (username, password, created_at) VALUES ('Cesar Franco', 'cf987pass', '2024-07-01');
INSERT INTO tb_user (username, password, created_at) VALUES ('Diana Gomes', 'D_Gomes#', '2024-08-14');
INSERT INTO tb_user (username, password, created_at) VALUES ('Eduardo Reis', 'Ed_2024', '2024-09-30');
INSERT INTO tb_user (username, password, created_at) VALUES ('Fabiana Neves', 'Fabn@2024', '2024-11-05');
INSERT INTO tb_user (username, password, created_at) VALUES ('Guilherme Teles', 'gt_Teles!', '2024-12-19');
INSERT INTO tb_user (username, password, created_at) VALUES ('Helena Viana', 'HelaViana', '2025-01-07');
INSERT INTO tb_user (username, password, created_at) VALUES ('Igor Costa', 'IgorC25', '2025-02-22');
INSERT INTO tb_user (username, password, created_at) VALUES ('Karen Mendes', 'K-Mendes', '2025-03-17');
INSERT INTO tb_user (username, password, created_at) VALUES ('Luiz Barros', 'LuizB#', '2025-04-04');
INSERT INTO tb_user (username, password, created_at) VALUES ('Monica Perez', 'MonPz', '2025-05-13');
INSERT INTO tb_user (username, password, created_at) VALUES ('Nelson Dias', 'NelsonD', '2025-06-28');
INSERT INTO tb_user (username, password, created_at) VALUES ('Olivia Rangel', 'ORangel', '2025-07-16');
INSERT INTO tb_user (username, password, created_at) VALUES ('Paulo Queiroz', 'PQ_123', '2025-08-29');
INSERT INTO tb_user (username, password, created_at) VALUES ('Quiteria Santos', 'QSantos', '2024-01-05');
INSERT INTO tb_user (username, password, created_at) VALUES ('Ricardo Diniz', 'RicoDnz', '2024-02-18');
INSERT INTO tb_user (username, password, created_at) VALUES ('Sofia Abreu', 'SofiAbreu', '2024-04-03');
INSERT INTO tb_user (username, password, created_at) VALUES ('Thiago Lima', 'T_Lima', '2024-06-12');
INSERT INTO tb_user (username, password, created_at) VALUES ('Ursula Xavier', 'Uxavier', '2024-07-29');
INSERT INTO tb_user (username, password, created_at) VALUES ('Vitor Zamboni', 'VitoZ', '2024-09-08');
INSERT INTO tb_user (username, password, created_at) VALUES ('Wanda Yanez', 'WandyY', '2024-10-23');
INSERT INTO tb_user (username, password, created_at) VALUES ('Xavier Rocha', 'X_Rocha', '2024-12-01');
INSERT INTO tb_user (username, password, created_at) VALUES ('Yara Zucchi', 'YaraZ', '2025-01-15');
INSERT INTO tb_user (username, password, created_at) VALUES ('Zelia Brito', 'ZeliB', '2025-02-08');
INSERT INTO tb_user (username, password, created_at) VALUES ('Arthur Melo', 'ArtMelo', '2025-03-29');
INSERT INTO tb_user (username, password, created_at) VALUES ('Bruna Lima', 'BrnLima', '2025-04-18');
INSERT INTO tb_user (username, password, created_at) VALUES ('Daniel Salles', 'DanSal', '2025-05-09');
INSERT INTO tb_user (username, password, created_at) VALUES ('Elisa Torres', 'EliTor', '2025-06-03');
INSERT INTO tb_user (username, password, created_at) VALUES ('Felipe Alves', 'FelAlv', '2025-07-08');
INSERT INTO tb_user (username, password, created_at) VALUES ('Gabriela Nunes', 'GabNunes', '2025-08-04');
INSERT INTO tb_user (username, password, created_at) VALUES ('Henrique Paz', 'HenPaz', '2025-09-01');
INSERT INTO tb_user (username, password, created_at) VALUES ('Ingrid Fogaça', 'IngFog', '2025-10-02');
INSERT INTO tb_user (username, password, created_at) VALUES ('Jorge Vilar', 'JorgVil', '2024-03-20');
INSERT INTO tb_user (username, password, created_at) VALUES ('Laura Dias', 'LauraDi', '2024-05-08');
INSERT INTO tb_user (username, password, created_at) VALUES ('Marcelo Cruz', 'MarCruz', '2024-06-20');
INSERT INTO tb_user (username, password, created_at) VALUES ('Natasha Lins', 'NatLins', '2024-08-05');
INSERT INTO tb_user (username, password, created_at) VALUES ('Otavio Gomes', 'OtaGom', '2024-09-15');
INSERT INTO tb_user (username, password, created_at) VALUES ('Priscila Leal', 'PriLeal', '2024-11-01');
INSERT INTO tb_user (username, password, created_at) VALUES ('Quirino Rocha', 'QuiRoch', '2024-12-10');
INSERT INTO tb_user (username, password, created_at) VALUES ('Renata Abreu', 'ReAbreu', '2025-01-28');
INSERT INTO tb_user (username, password, created_at) VALUES ('Sergio Bueno', 'SerBue', '2025-03-05');
INSERT INTO tb_user (username, password, created_at) VALUES ('Tatiane Faria', 'TatFar', '2025-04-10');
INSERT INTO tb_user (username, password, created_at) VALUES ('Uriel Mendes', 'UriMen', '2025-05-20');
INSERT INTO tb_user (username, password, created_at) VALUES ('Vivian Nunes', 'VivNun', '2025-06-19');
INSERT INTO tb_user (username, password, created_at) VALUES ('Wilson Paz', 'WilPaz', '2025-07-27');
INSERT INTO tb_user (username, password, created_at) VALUES ('Yasmin Costa', 'YasCos', '2025-08-19');
INSERT INTO tb_user (username, password, created_at) VALUES ('Zenon Lima', 'ZenLim', '2025-09-14');
INSERT INTO tb_user (username, password, created_at) VALUES ('Aline Barros', 'AlinBar', '2025-10-20');
INSERT INTO tb_user (username, password, created_at) VALUES ('Bruno Santos', 'BrunSan', '2024-04-29');

INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Revisar código do projeto', 'Fazer code review do módulo de autenticação', false, '2024-11-20', '2024-11-28', null, 1, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Criar testes unitários', 'Escrever testes JUnit para o serviço de tarefas', false, '2024-11-18', '2024-11-25', '2024-11-18', 1, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Atualizar documentação', 'Revisar README e documentar endpoints da API', false, '2024-11-10', '2024-11-17', '2024-11-10', 2, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Configurar CI/CD', 'Adicionar pipeline no GitHub Actions para build e testes', true, '2024-11-05', '2024-11-12', '2024-11-05', 0, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Refatorar service de usuário', 'Melhorar nomenclatura e remover duplicações', false, '2024-11-12', '2024-11-19', '2024-11-12', 1, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Criar página de tarefas', 'Desenvolver telas em React para listar e editar tarefas', true, '2024-11-01', '2024-11-08', '2024-11-01', 2, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Implementar validações', 'Adicionar validações de formulário no backend', false, '2024-11-14', '2024-11-21', '2024-11-14', 0, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Configurar Docker', 'Criar Dockerfile e docker-compose para ambiente dev', false, '2024-11-03', '2024-11-10', '2024-11-03', 1, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Otimizar consultas SQL', 'Adicionar índices e revisar queries lentas', true, '2024-11-07', '2024-11-14', '2024-11-07', 0, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Criar endpoints de relatório', 'Gerar relatório de tarefas concluídas no mês', false, '2024-11-15', '2024-11-22', '2024-11-15', 2, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Refatorar componentes antigos', 'Atualizar componentes React para usar hooks modernos', true, '2024-10-03', '2024-10-10', '2024-10-03', 1, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Configurar integração contínua', 'Criar pipeline no GitHub Actions para testes e deploy', false, '2024-12-01', '2024-12-08', '2024-12-01', 0, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Atualizar documentação técnica', 'Revisar README e adicionar instruções de setup', true, '2024-09-22', '2024-09-29', '2024-09-22', 2, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Implementar autenticação JWT', 'Adicionar fluxo de login e refresh token', false, '2024-11-08', '2024-11-15', '2024-11-08', 0, 5);
INSERT INTO tb_task (title, description, completed, created_at, due_date, updated_at, priority, user_id) VALUES ('Criar testes de integração', 'Escrever testes para rotas principais da API', false, '2024-08-19', '2024-08-26', '2024-08-19', 1, 5);

